name: clang-format Check
on:
  push:
    paths:
      - '.github/workflows/clang-format-check.yml'
      - 'include/**'
      - 'tests/**'
      - 'benchmark/**'
    branches: [ ci_workflows ]
  pull_request:
    paths:
      - '.github/workflows/clang-format-check.yml'
      - 'include/**'
      - 'tests/**'
      - 'benchmark/**'
    branches: [ ci_workflows ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'include'
          - 'tests'
          - 'benchmark'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
        fallback-style: 'WebKit'
